apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sqlserverapp.service.name }}
spec:
  selector:
    app: {{ .Values.sqlserverapp.appname }}
  ports:
  - port: {{ .Values.sqlserverapp.service.port }}
    targetPort: 1433
  type: {{ .Values.sqlserverapp.service.type }}
