# Default values for ln-az-func.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
funcapp: 
  replicaCount: 1
  appname: func-app
  env: dev
  image: "rakeshkumarreddy907/test:latest"

service:
  type: LoadBalancer
  port: 9001

secrets:
  storagekey: <key-here>

