data:
  AzureWebJobsStorage: {{ .Values.secrets.storagekey }}
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0LWlzb2xhdGVk
  AzureWebJobsSecretStorageType: ZmlsZXM=
  QueueCS: {{ .Values.secrets.storagekey }}
apiVersion: v1
kind: Secret
metadata:
  name: func-secret