apiVersion: v1
kind: PersistentVolume
metadata:
  name: func-pv
  labels:
    app: func-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity: 
    storage: 4Gi
  local:
    path: /mnt/rakesh/ssd
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop