apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path-based
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: testingrakesh.com
    http:
      paths:
      # - path: /testing
      #   pathType: Exact
      #   backend:
      #     service:
      #       name: nginx-svc
      #       port:
      #         number: {{ .Values.nginxapp.service.port }}  
      # - path: /lala
      #   pathType: Exact
      #   backend:
      #     service:
      #       name: func-svc
      #       port:
      #         number: {{ .Values.funcapp.service.port }}   
      - path: /testing/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-svc
            port:
              number: {{ .Values.nginxapp.service.port }}         
      - path: /lala/?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: func-svc
            port:
              number: {{ .Values.funcapp.service.port }}                         
  ingressClassName: nginx
