apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx    
spec:
  selector:
    app: nginx
  # type: {{ .Values.nginxapp.service.type }}
  ports:
  - port: {{ .Values.nginxapp.service.port }}
    targetPort: 80
    protocol: TCP